spring:
  application:
    name: "gatewayserver"
  config:
    import:
      - "configserver:http://configserver:8071/"
#  config:
#    import:
#      - "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      global-filter:
        websocket-routing:
          enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
#          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
          issuer-uri: http://keycloak:8080/realms/master


#
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted
    health:
      probes:
        enabled: true


# Write description for Eureka Server
info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

# Logging
logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.web.cors: DEBUG
    com:
      eazybytes:
        gatewayserver: DEBUG