spring:
  application:
    name: "eurekaserver"
  config:
    import: "configserver:${SPRING_CONFIG_IMPORT:http://localhost:8071/}"
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:dev}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true