version: '3.8'

services:
  payment-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      - SERVER_PORT=50051
      - SERVER_BASE_URL=http://localhost:9080
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DATABASE=payment_api
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - PAYPAL_SANDBOX=true
      - SOLANA_ENDPOINT=https://api.devnet.solana.com
      - SOLANA_PRIVATE_KEY=${SOLANA_PRIVATE_KEY}
      - SOLANA_PROGRAM_ID=${SOLANA_PROGRAM_ID}
      - TS_SERVER_URL=http://ts-api:8081
      - TS_CLIENT_PRIVATE_KEY=${SOLANA_PROGRAM_ID}
      - TS_CLIENT_TIMEOUT_SEC=10
    depends_on:
      - mongo
      - ts-api
    restart: unless-stopped

  ts-api:
    build:
      context: ./ts-api
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: