spring:
  application:
    name: "configserver"
  profiles:
    active: git # READ CONFIG FROM GIT
#   active: native READ CONFIG FROM LOCAL COMPUTER

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/koshikovme/agrichain-invest-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

#        native:
#          search-locations: "classpath:/config" INSIDE your resources folder inside this project
#          search-locations: "file:///C://Users..." INSIDE your file system

server:
  port: 8071


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true