// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: notification.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNKNOWN NotificationType = 0
	NotificationType_REGISTRATION              NotificationType = 1
	NotificationType_LOGIN                     NotificationType = 2
	NotificationType_INVESTMENT_SUCCESS        NotificationType = 3
	NotificationType_INVESTED_IN_YOU           NotificationType = 4
	NotificationType_OTHER                     NotificationType = 5
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNKNOWN",
		1: "REGISTRATION",
		2: "LOGIN",
		3: "INVESTMENT_SUCCESS",
		4: "INVESTED_IN_YOU",
		5: "OTHER",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNKNOWN": 0,
		"REGISTRATION":              1,
		"LOGIN":                     2,
		"INVESTMENT_SUCCESS":        3,
		"INVESTED_IN_YOU":           4,
		"OTHER":                     5,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

type NotificationChannel int32

const (
	NotificationChannel_NOTIFICATION_CHANNEL_UNKNOWN NotificationChannel = 0
	NotificationChannel_EMAIL                        NotificationChannel = 1
	NotificationChannel_WEB                          NotificationChannel = 2
)

// Enum value maps for NotificationChannel.
var (
	NotificationChannel_name = map[int32]string{
		0: "NOTIFICATION_CHANNEL_UNKNOWN",
		1: "EMAIL",
		2: "WEB",
	}
	NotificationChannel_value = map[string]int32{
		"NOTIFICATION_CHANNEL_UNKNOWN": 0,
		"EMAIL":                        1,
		"WEB":                          2,
	}
)

func (x NotificationChannel) Enum() *NotificationChannel {
	p := new(NotificationChannel)
	*p = x
	return p
}

func (x NotificationChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[1].Descriptor()
}

func (NotificationChannel) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[1]
}

func (x NotificationChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationChannel.Descriptor instead.
func (NotificationChannel) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

type AuthNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"` // email пользователя
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`   // имя пользователя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthNotificationRequest) Reset() {
	*x = AuthNotificationRequest{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthNotificationRequest) ProtoMessage() {}

func (x *AuthNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthNotificationRequest.ProtoReflect.Descriptor instead.
func (*AuthNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *AuthNotificationRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthNotificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthNotificationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                // Инвестор
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                                                                                 // email пользователя
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // имя пользователя
	Type          NotificationType       `protobuf:"varint,4,opt,name=type,proto3,enum=grpc.NotificationType" json:"type,omitempty"`                                                       // тип уведомления
	Channels      []NotificationChannel  `protobuf:"varint,5,rep,packed,name=channels,proto3,enum=grpc.NotificationChannel" json:"channels,omitempty"`                                     // EMAIL и WEB
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // subject, body, url
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNotificationRequest) Reset() {
	*x = UserNotificationRequest{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotificationRequest) ProtoMessage() {}

func (x *UserNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotificationRequest.ProtoReflect.Descriptor instead.
func (*UserNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *UserNotificationRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserNotificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserNotificationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserNotificationRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNKNOWN
}

func (x *UserNotificationRequest) GetChannels() []NotificationChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *UserNotificationRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *SendNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendNotificationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\x04grpc\"\\\n" +
	"\x17AuthNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xc5\x02\n" +
	"\x17UserNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12*\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.grpc.NotificationTypeR\x04type\x125\n" +
	"\bchannels\x18\x05 \x03(\x0e2\x19.grpc.NotificationChannelR\bchannels\x12G\n" +
	"\bmetadata\x18\x06 \x03(\v2+.grpc.UserNotificationRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\x18SendNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*\x86\x01\n" +
	"\x10NotificationType\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fREGISTRATION\x10\x01\x12\t\n" +
	"\x05LOGIN\x10\x02\x12\x16\n" +
	"\x12INVESTMENT_SUCCESS\x10\x03\x12\x13\n" +
	"\x0fINVESTED_IN_YOU\x10\x04\x12\t\n" +
	"\x05OTHER\x10\x05*K\n" +
	"\x13NotificationChannel\x12 \n" +
	"\x1cNOTIFICATION_CHANNEL_UNKNOWN\x10\x00\x12\t\n" +
	"\x05EMAIL\x10\x01\x12\a\n" +
	"\x03WEB\x10\x022\xa3\x02\n" +
	"\x13NotificationService\x12]\n" +
	"\x1cSendRegistrationNotification\x12\x1d.grpc.AuthNotificationRequest\x1a\x1e.grpc.SendNotificationResponse\x12V\n" +
	"\x15SendLoginNotification\x12\x1d.grpc.AuthNotificationRequest\x1a\x1e.grpc.SendNotificationResponse\x12U\n" +
	"\x14SendUserNotification\x12\x1d.grpc.UserNotificationRequest\x1a\x1e.grpc.SendNotificationResponseB\n" +
	"Z\bpkg/grpcb\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_notification_proto_goTypes = []any{
	(NotificationType)(0),            // 0: grpc.NotificationType
	(NotificationChannel)(0),         // 1: grpc.NotificationChannel
	(*AuthNotificationRequest)(nil),  // 2: grpc.AuthNotificationRequest
	(*UserNotificationRequest)(nil),  // 3: grpc.UserNotificationRequest
	(*SendNotificationResponse)(nil), // 4: grpc.SendNotificationResponse
	nil,                              // 5: grpc.UserNotificationRequest.MetadataEntry
}
var file_notification_proto_depIdxs = []int32{
	0, // 0: grpc.UserNotificationRequest.type:type_name -> grpc.NotificationType
	1, // 1: grpc.UserNotificationRequest.channels:type_name -> grpc.NotificationChannel
	5, // 2: grpc.UserNotificationRequest.metadata:type_name -> grpc.UserNotificationRequest.MetadataEntry
	2, // 3: grpc.NotificationService.SendRegistrationNotification:input_type -> grpc.AuthNotificationRequest
	2, // 4: grpc.NotificationService.SendLoginNotification:input_type -> grpc.AuthNotificationRequest
	3, // 5: grpc.NotificationService.SendUserNotification:input_type -> grpc.UserNotificationRequest
	4, // 6: grpc.NotificationService.SendRegistrationNotification:output_type -> grpc.SendNotificationResponse
	4, // 7: grpc.NotificationService.SendLoginNotification:output_type -> grpc.SendNotificationResponse
	4, // 8: grpc.NotificationService.SendUserNotification:output_type -> grpc.SendNotificationResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		EnumInfos:         file_notification_proto_enumTypes,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
