database:
  host: "localhost"
  user: "postgres"
  password: "pos"
  dbname: "postgres"
  port: 5432
  sslmode: "disable"

smtp:
  sender_email: "email@example.com"
  username: "mailtrap username"
  password: "mailtrap password"

kafka:
  topic: "notifications"
  
ports:
  http: 8081
  grpc: 8080
  ws: 6969
  kafka: ["localhost:9093"]